### ISSUE TITLE
Don't create a lambda for os.pause

### ISSUE THREAD

**Issue by ZachOhara** [zachw000/Project_Euler#1]
Adding this just creates a layer of obscurity between the methods in your program and what's actually happening.

Also, because functions in Python are objects themselves, you don't even need a lambda ther. Just say pause = os.pause. As long as you don't include any parenthesis, you'll be fine.

**Comment by zachw000** [comment]
@ZachOhara The point of the lambda was so the pause function could easily be called, and personally I find this easier to use rather than to type os.system("PAUSE") every time I need to call the operating system's pause function. Please explain how this creates a "layer of obscurity"
